### PR TITLE
Avoid excessive setPosition (with focus in element)

### PR DESCRIPTION
**Pull request by garex**
* Use null instead of zero to skip setPosition

Also no tests here.

### CODE REVIEW

**Comment by leodido** [comment]
Can you please explain why do you think the initial value should be set to null?

If I remember correctly it was set to 0 since the `<input_target>.selectionStart` (at the DOM level), that is a 1-based index, is set with a 0 at the start time.

**Comment by garex** [comment]
Because it's a bug, when last control with this directive got focused on page load.

**Comment by leodido** [comment]
I can be wrong but but this not seems to be true to me.

As you can see in the following screenshot, at the page load, the **[document.activeElement](https://developer.mozilla.org/it/docs/Web/API/Document/activeElement)** corresponds to the body.


screenshot from 2017-05-16 14-33-54
screenshot from 2017-05-16 14-33-38

Only when you press the TAB the input get focused and so **document.activeElement** returns the input !

So please provide some example/snippet/plunkr/etc. demonstrating the opposite.

**Comment by garex** [comment]
https://plnkr.co/edit/AaRKUvXoJinXVc8gmmoa?p=preview

Just add ng-model to input and you will get it.

**Comment by leodido** [comment]
@garex perfect, thanks ! :+1: 

You're right.

In the case the `ng-model` is present we need to avoid to focus the input (first digest cycle).

I am just wondering whether exists another method to avoid focus ...

Furthermore I am wondering what values **getSelection** (so also **getPosition**) should return when called in this "initial" situation (no initial **setPosition**). I think that to have the answer we should look to the DOM.

Please help with this further investigation!

Then I'll merge this and we'll concentrate on testing this enhancement.

**Comment by garex** [comment]
> Please help with this further investigation!

Are you serious? )) I started it only as of setSelectionText feature. And after that you completely destroyed my dream -- you want my help? Noway ))

**Pull request closed without merging**
